# Generated by Django 3.1.7 on 2021-03-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('f_name', models.CharField(max_length=10)),
                ('l_name', models.CharField(max_length=10)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('address_1', models.TextField()),
                ('address_2', models.TextField()),
                ('password', models.TextField()),
                ('mail', models.EmailField(max_length=254)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('order_id', models.IntegerField()),
            ],
        ),
    ]
