# Generated by Django 3.1.6 on 2021-04-02 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_auto_20210320_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='order_id',
        ),
    ]
