# Generated by Django 3.1.6 on 2021-03-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('description', models.TextField(default='Write description..')),
                ('year', models.IntegerField()),
                ('publisher', models.CharField(max_length=30)),
                ('platform', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='Product_img/images')),
            ],
        ),
    ]
