# Generated by Django 3.1.6 on 2021-04-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourGames', '0002_auto_20210320_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(default='default.png', upload_to='Product_img/images'),
        ),
    ]
