# Generated by Django 3.1.6 on 2021-04-02 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0003_remove_payment_cart_id'),
        ('Customer', '0004_remove_customer_order_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ourGames', '0002_auto_20210320_2055'),
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('games', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ourGames.game')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
