# Generated by Django 3.1.5 on 2021-03-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginInfo', '0002_auto_20210323_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='default.png', upload_to='Product_img/images'),
        ),
    ]
