# Generated by Django 3.1.6 on 2021-04-05 12:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ourGames', '0002_auto_20210320_2055'),
        ('loginInfo', '0003_customer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginInfo.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ourGames.game')),
            ],
        ),
    ]
