# Generated by Django 3.1.6 on 2021-04-05 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginInfo', '0005_order_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
    ]
