# Generated by Django 3.1.7 on 2021-03-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('name', models.CharField(max_length=10)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('title', models.CharField(max_length=30)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('publisher', models.CharField(max_length=30)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('platform', models.CharField(max_length=10)),
            ],
        ),
    ]
