# Generated by Django 3.1.6 on 2021-03-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0002_games_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='categories',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='games',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
